version: '3.8'
services:
  db:
    image: postgres:14.8-alpine
    container_name: postgres-14.8
    volumes:
      - postgres:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: zack_fb_clone_db 
      POSTGRES_USER: <User>
      POSTGRES_PASSWORD: <Password>
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      # command: bash -c "pwd && ls -la && cd ../.. && ls -la && cd /root && ls -la"
    environment:
      DB_HOST: db
      DB_NAME: zack_fb_clone_db
      DB_USERNAME: <User>
      DB_PASSWORD: <Password>
      DB_PORT: 5432
    volumes:
      - .:/zack-fb-clone
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - "db:database"
volumes:
  postgres: {}

